package core.user;

public enum Authorization {
    ADMINISTRATOR, INSTRUCTOR, STUDENT,
    ADMINISTRATOR_INSTRUCTOR, ADMINISTRATOR_STUDENT, INSTRUCTOR_STUDENT,
    ADMINISTRATOR_INSTRUCTOR_STUDENT,
}
